name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

# A release is only created in the GitHub UI when you click publish release.concurrency:
# https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
on:
  release:
    types: [published]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install -g bats
      - run: bats -v
